# Generated by Django 5.2 on 2025-04-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='LINK PRODUTO'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='TÍTULO DO PRODUTO'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='VALOR DO PRODUTO'),
        ),
    ]
