# Generated by Django 5.2 on 2025-04-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_produto_imagem_url_alter_produto_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='fonte',
            field=models.CharField(default='', max_length=20),
        ),
    ]
